name: Testes ViewSets

on:
  push:
    branches:
      - viewsets-tests
  pull_request:
    branches:
      - serializers-tests

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: python -m pip install poetry==2.4.1

      - name: Instalar dependencias
        run: poetry install --no-interaction

      - name: Executar testes
        run: poetry run pytest -q
